Traceback (most recent call last):
  File "visualize.py", line 7, in <module>
    from viss2 import create_interactive_connectivity111
ImportError: cannot import name 'create_interactive_connectivity111' from 'viss2' (/data1/malavika/da6401_assgn3/attn_encoder_decoder/viss2.py)
